name: SonarCloud Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: |
        npm test -- --coverage --coverageReporters=lcov --coverageReporters=text --coverageReporters=json-summary
        echo "✅ Tests completed with coverage"

    - name: Verify coverage file
      run: |
        if [ -f coverage/lcov.info ]; then
          echo "✅ LCOV coverage file found"
          echo "Coverage file size: $(wc -c < coverage/lcov.info) bytes"
        else
          echo "❌ LCOV coverage file not found"
          ls -la coverage/
          exit 1
        fi

    - name: Check SONAR_TOKEN
      run: |
        if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
          echo "❌ SONAR_TOKEN is not configured"
          echo "Please configure SONAR_TOKEN in GitHub repository secrets"
          echo "See setup instructions in SONARCLOUD_README.md"
          exit 1
        else
          echo "✅ SONAR_TOKEN is configured"
        fi

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Quality Gate check
      uses: sonarqube-quality-gate-action/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

    - name: Upload coverage to artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30

    - name: Comment PR with SonarCloud results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const projectKey = 'HectorIFC_hc-lisp';
          const sonarUrl = `https://sonarcloud.io/project/overview?id=${projectKey}`;
          const prUrl = `https://sonarcloud.io/project/pull_requests?id=${projectKey}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 📊 SonarCloud Analysis
            
            The SonarCloud analysis has been completed for this PR.
            
            🔍 **[View detailed results on SonarCloud](${sonarUrl})**
            📈 **[View PR analysis](${prUrl})**
            
            Key metrics will be available after the analysis completes.
            
            If you see authentication issues, please ensure SONAR_TOKEN is configured in repository secrets.`
          });
